"""Lightweight waste signal scanner for governance sweep.

Reads a session transcript and produces a JSON metrics summary.
Does NOT do deep analysis — that's reserved for staff-level post-mortems.
"""
import json
import sys
import os
from collections import Counter
from datetime import datetime

# Waste signal patterns to scan for
WASTE_SIGNALS = {
    "ast.parse": "SYNTAX_ONLY_VERIFICATION",
    "pip install": "VIRTUALENV_DRIFT",
    "git add -A": "DIRTY_VCS_STAGING",
    "git add .": "DIRTY_VCS_STAGING",
    "git push --force": "DIRTY_VCS_STAGING",
    "total_mem": "HALLUCINATION",
    "ELOOP": "CIRCULAR_SYMLINK_RECURSION",
}

# Rework indicators (heuristic — count repeated edits to same file)
REWORK_INDICATORS = [
    "The following changes were made",  # file edit tool output
    "error", "Error", "ERROR",
    "Traceback",
    "SyntaxError",
    "ImportError",
    "ModuleNotFoundError",
    "AttributeError",
]


def scan_transcript(transcript_path):
    """Scan a transcript and return waste metrics."""
    steps = []
    with open(transcript_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                steps.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    total_steps = len(steps)
    if total_steps == 0:
        return None

    # Count waste signals
    signal_counts = Counter()
    pattern_counts = Counter()
    error_steps = 0
    edit_steps = 0

    for step in steps:
        content = step.get("content", "") or ""

        # Check for waste signals
        for signal, pattern in WASTE_SIGNALS.items():
            if signal in content:
                signal_counts[signal] += 1
                pattern_counts[pattern] += 1

        # Count error indicators (heuristic for rework)
        for indicator in REWORK_INDICATORS:
            if indicator in content:
                if indicator in ("error", "Error", "ERROR", "Traceback",
                                 "SyntaxError", "ImportError",
                                 "ModuleNotFoundError", "AttributeError"):
                    error_steps += 1
                elif indicator == "The following changes were made":
                    edit_steps += 1
                break  # Only count once per step

    # Estimate waste rate (conservative heuristic)
    # Direct waste signals are definite waste
    direct_waste = sum(signal_counts.values())

    # Error density heuristic: if >30% of steps have errors, likely rework loops
    error_rate = error_steps / total_steps if total_steps > 0 else 0
    estimated_rework = 0
    if error_rate > 0.3:
        estimated_rework = int(error_steps * 0.5)  # Assume 50% of error steps are rework
        pattern_counts["REWORK_LOOP"] += estimated_rework

    total_waste = direct_waste + estimated_rework
    waste_rate = round(total_waste / total_steps, 3) if total_steps > 0 else 0

    # Get top patterns
    top_patterns = pattern_counts.most_common(3)

    # Determine session timestamps
    first_ts = None
    last_ts = None
    for step in steps:
        content = step.get("content", "") or ""
        if "current local time is:" in content.lower():
            # Try to extract timestamp
            try:
                idx = content.lower().index("current local time is:")
                ts_str = content[idx + 22:idx + 47].strip().rstrip(".")
                first_ts = first_ts or ts_str
                last_ts = ts_str
            except (ValueError, IndexError):
                pass

    return {
        "total_steps": total_steps,
        "waste_signals": dict(signal_counts),
        "pattern_counts": dict(pattern_counts),
        "error_steps": error_steps,
        "edit_steps": edit_steps,
        "estimated_waste_rate": waste_rate,
        "estimated_wasted_steps": total_waste,
        "estimated_productive_steps": total_steps - total_waste,
        "top_patterns": [{"pattern": p, "count": c} for p, c in top_patterns],
        "first_timestamp": first_ts,
        "last_timestamp": last_ts,
        "scan_type": "lightweight_sweep",
        "scanned_at": datetime.now().isoformat(),
    }


def to_session_metrics(session_id, scan_result):
    """Convert scan result to session_metrics JSON format."""
    patterns = {}
    for p in scan_result.get("top_patterns", []):
        patterns[p["pattern"]] = p["count"]

    return {
        "session_id": session_id,
        "total_steps": scan_result["total_steps"],
        "wasted_steps": scan_result["estimated_wasted_steps"],
        "productive_steps": scan_result["estimated_productive_steps"],
        "waste_rate": scan_result["estimated_waste_rate"],
        "patterns": patterns,
        "scan_type": "lightweight_sweep",
        "scanned_at": scan_result["scanned_at"],
        "note": "Auto-generated by governance sweep. Run staff post-mortem for deep analysis.",
    }


def main():
    if len(sys.argv) < 2:
        print("Usage: sweep_session.py <transcript_path> [taxonomy_path] [--summary-only]",
              file=sys.stderr)
        sys.exit(1)

    transcript_path = sys.argv[1]
    summary_only = "--summary-only" in sys.argv

    if not os.path.exists(transcript_path):
        print(f"Transcript not found: {transcript_path}", file=sys.stderr)
        sys.exit(1)

    result = scan_transcript(transcript_path)
    if result is None:
        print("{}", file=sys.stdout)
        sys.exit(0)

    if summary_only:
        summary = {
            "steps": result["total_steps"],
            "waste_rate": result["estimated_waste_rate"],
            "top_pattern": result["top_patterns"][0]["pattern"] if result["top_patterns"] else "clean",
        }
        print(json.dumps(summary))
    else:
        # Extract session_id from path
        parts = transcript_path.split("/")
        session_id = "unknown"
        for i, part in enumerate(parts):
            if part == "brain" and i + 1 < len(parts):
                session_id = parts[i + 1][:8]
                break

        metrics = to_session_metrics(session_id, result)
        print(json.dumps(metrics, indent=2))


__all__ = [
    "REWORK_INDICATORS",
    "WASTE_SIGNALS",
    "main",
    "scan_transcript",
    "to_session_metrics",
]
